'use client'

import { useMemo, useState } from 'react'
import { useInventoryStore, type InventoryCategory, type InventoryMovementType, type InventoryUnit } from '@/store/useInventoryStore'
import { useSupplierStore } from '@/store/useSupplierStore'
import { formatCurrency } from '@/lib/formatters'

const categories: InventoryCategory[] = ['siding', 'soffit', 'fascia', 'roofing', 'fasteners', 'sealants', 'tools', 'safety', 'other']
const units: InventoryUnit[] = ['pcs', 'box', 'bundle', 'roll', 'pail', 'tube', 'sqft', 'linear_ft']
type TabKey = 'materials' | 'tools' | 'consumables' | 'protection' | 'low' | 'moves' | 'all'
const tabs: Array<{ key: TabKey; label: string; cats: InventoryCategory[] }> = [
  { key: 'materials', label: 'Matériaux', cats: ['siding', 'soffit', 'fascia', 'roofing'] },
  { key: 'tools', label: 'Outils', cats: ['tools'] },
  { key: 'consumables', label: 'Consommables', cats: ['fasteners', 'sealants'] },
  { key: 'protection', label: 'Protection', cats: ['safety'] },
  { key: 'low', label: 'Bas stock', cats: [] },
  { key: 'moves', label: 'Mouvements', cats: [] },
  { key: 'all', label: 'Tout', cats: [] },
]

export default function InventoryPage() {
  const { items = [], movements = [], addItem, updateItem, moveStock } = useInventoryStore()
  const allSuppliers = useSupplierStore(s => s.suppliers)
  const suppliers = useMemo(() => (allSuppliers || []).filter(x => x.active), [allSuppliers])
  const [tab, setTab] = useState<TabKey>('materials')
  const [form, setForm] = useState({ name: '', category: 'siding' as InventoryCategory, unit: 'pcs' as InventoryUnit, location: 'Entrepôt principal', supplier: '', quantity: '', min: '', reorder: '', cost: '' })
  const lowItems = useMemo(() => items.filter(i => (Number(i.quantity) || 0) - (Number(i.reserved) || 0) <= (Number(i.minQuantity) || 0)), [items])
  const totalValue = useMemo(() => items.reduce((s, i) => s + (Number(i.quantity) || 0) * (Number(i.unitCost) || 0), 0), [items])
  const reservedValue = useMemo(() => items.reduce((s, i) => s + (Number(i.reserved) || 0) * (Number(i.unitCost) || 0), 0), [items])
  const active = tabs.find(t => t.key === tab) || tabs[0]
  const activeItems = useMemo(() => {
    if (tab === 'all' || tab === 'moves') return items
    if (tab === 'low') return lowItems
    return items.filter(i => active.cats.includes(i.category))
  }, [tab, items, lowItems, active])

  function setField(key: keyof typeof form, value: string) { setForm(f => ({ ...f, [key]: value })) }
  function createItem() {
    if (!form.name.trim()) return
    addItem({ name: form.name.trim(), category: form.category, unit: form.unit, location: form.location || 'Entrepôt principal', supplier: form.supplier || undefined, quantity: Number(form.quantity) || 0, minQuantity: Number(form.min) || 0, reorderQuantity: Number(form.reorder) || 0, unitCost: Number(form.cost) || 0, notes: '' })
    setForm(f => ({ ...f, name: '', supplier: '', quantity: '', min: '', reorder: '', cost: '' }))
  }

  return <main className="min-h-screen px-4 pb-28 pt-6 text-white inventory-page"><div className="mx-auto max-w-6xl space-y-4">
    <section className="rounded-3xl border border-white/10 bg-white/5 p-5"><h1 className="text-3xl font-black">📦 Inventaire entrepôt</h1><p className="mt-2 text-lg text-white/70">Stock physique réel. Le catalogue reste séparé pour les produits et prix facturables.</p></section>
    <section className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Metric title="Valeur stock" value={formatCurrency(totalValue)} sub={`${items.length} produits`} /><Metric title="Réservé" value={formatCurrency(reservedValue)} sub="Pour jobs" /><Metric title="Bas stock" value={`${lowItems.length}`} sub="À recommander" danger={lowItems.length > 0} /><Metric title="Mouvements" value={`${movements.length}`} sub="Entrées / sorties" /></section>
    <section className="rounded-3xl border border-white/10 bg-white/5 p-3"><div className="grid gap-2 md:grid-cols-4 lg:grid-cols-7">{tabs.map(t => <button key={t.key} onClick={() => setTab(t.key)} className={`rounded-2xl border p-4 text-left ${tab === t.key ? 'border-cyan-300/70 bg-cyan-400/15' : 'border-white/10 bg-black/20'}`}><b className="block text-lg">{t.label}</b></button>)}</div></section>
    {lowItems.length > 0 && <section className="rounded-3xl border border-amber-400/30 bg-amber-400/10 p-4"><h2 className="text-2xl font-black text-amber-200">⚠️ Alertes réapprovisionnement</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{lowItems.map(i => <div key={i.id} className="rounded-2xl border border-amber-400/20 bg-black/20 p-4"><b className="text-xl">{i.name}</b><p className="text-lg text-amber-100">Disponible: {(i.quantity || 0) - (i.reserved || 0)} {i.unit} · min: {i.minQuantity}</p><p className="text-base text-white/65">Commander: {i.reorderQuantity} · {i.supplier || 'fournisseur —'}</p></div>)}</div></section>}
    <section className="rounded-3xl border border-white/10 bg-white/5 p-4"><h2 className="text-2xl font-black">Ajouter un item</h2><div className="mt-3 grid gap-3 lg:grid-cols-4"><input className="big-field" value={form.name} onChange={e => setField('name', e.target.value)} placeholder="Nom"/><select className="big-field" value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value as InventoryCategory }))}>{categories.map(c => <option key={c} value={c}>{c}</option>)}</select><select className="big-field" value={form.unit} onChange={e => setForm(f => ({ ...f, unit: e.target.value as InventoryUnit }))}>{units.map(u => <option key={u} value={u}>{u}</option>)}</select><input className="big-field" value={form.location} onChange={e => setField('location', e.target.value)} placeholder="Emplacement"/>{suppliers.length ? <select className="big-field" value={form.supplier} onChange={e => setField('supplier', e.target.value)}><option value="">Choisir fournisseur</option>{suppliers.map(s => <option key={s.id} value={s.name}>{s.name}</option>)}</select> : <input className="big-field" value={form.supplier} onChange={e => setField('supplier', e.target.value)} placeholder="Fournisseur"/>}<input className="big-field" value={form.quantity} onChange={e => setField('quantity', e.target.value)} inputMode="decimal" placeholder="Quantité"/><input className="big-field" value={form.min} onChange={e => setField('min', e.target.value)} inputMode="decimal" placeholder="Minimum"/><input className="big-field" value={form.reorder} onChange={e => setField('reorder', e.target.value)} inputMode="decimal" placeholder="À commander"/><input className="big-field" value={form.cost} onChange={e => setField('cost', e.target.value)} inputMode="decimal" placeholder="Coût unitaire"/><button className="big-button lg:col-span-3" onClick={createItem}>Ajouter</button></div><p className="mt-3 text-base text-white/60">Les fournisseurs viennent de /suppliers. Si la liste est vide, le champ manuel reste disponible.</p></section>
    {tab !== 'moves' && <section className="rounded-3xl border border-white/10 bg-white/5 p-4"><h2 className="text-2xl font-black">{active.label}</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{activeItems.length === 0 ? <p className="text-lg text-white/60">Aucun item.</p> : activeItems.map(item => <InventoryCard key={item.id} item={item} updateItem={updateItem} moveStock={moveStock} />)}</div></section>}
    <section className="rounded-3xl border border-white/10 bg-white/5 p-4"><h2 className="text-2xl font-black">Mouvements récents</h2><div className="mt-3 space-y-2">{movements.slice(0, tab === 'moves' ? 100 : 20).map(m => <div key={m.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex items-start justify-between gap-2"><div><b className="text-xl">{m.itemName}</b><p className="text-base text-white/65">{m.type} · {m.jobName || '—'} · {new Date(m.createdAt).toLocaleString('fr-CA')}</p><p className="text-base text-white/60">{m.note || 'Aucune note'}</p></div><strong className="text-2xl text-cyan-300">{m.quantity}</strong></div></div>)}{movements.length === 0 && <p className="text-lg text-white/60">Aucun mouvement.</p>}</div></section>
  </div></main>
}

function Metric({ title, value, sub, danger }: { title: string; value: string; sub: string; danger?: boolean }) { return <div className="rounded-3xl border border-white/10 bg-white/5 p-4 min-w-0 overflow-hidden"><p className="text-base font-black text-white/70">{title}</p><p className={`mt-2 font-black ${danger ? 'text-amber-300' : 'text-cyan-300'}`} style={{ fontSize: 'clamp(25px,8vw,34px)', lineHeight: 1.05, letterSpacing: '-0.04em', overflowWrap: 'anywhere' }}>{value}</p><p className="mt-1 text-base text-white/70">{sub}</p></div> }
function InventoryCard({ item, updateItem, moveStock }: any) { const [qty, setQty] = useState(''); const [job, setJob] = useState(''); const [note, setNote] = useState(''); const available = (item.quantity || 0) - (item.reserved || 0); const low = available <= (item.minQuantity || 0); function move(type: InventoryMovementType) { const n = Number(qty); if (!n || n <= 0) return; moveStock({ itemId: item.id, type, quantity: n, jobName: job || undefined, note: note || undefined }); setQty(''); setJob(''); setNote('') } return <div className={`rounded-3xl border p-4 ${low ? 'border-amber-400/35 bg-amber-400/10' : 'border-white/10 bg-black/20'}`}><h3 className="text-2xl font-black">{item.name}</h3><p className="text-lg text-white/70">{item.category} · {item.location} · {item.supplier || 'fournisseur —'}</p><div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2"><Metric title="En stock" value={`${item.quantity} ${item.unit}`} sub={`Dispo ${available}`} danger={low}/><Metric title="Valeur" value={formatCurrency((item.quantity || 0) * (item.unitCost || 0))} sub={`${formatCurrency(item.unitCost || 0)} / ${item.unit}`} /></div><div className="mt-3 grid gap-2 md:grid-cols-3"><input className="big-field" value={qty} onChange={e => setQty(e.target.value)} inputMode="decimal" placeholder="Quantité"/><input className="big-field" value={job} onChange={e => setJob(e.target.value)} placeholder="Job"/><input className="big-field" value={note} onChange={e => setNote(e.target.value)} placeholder="Note"/></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><button className="big-button" onClick={() => move('in')}>Entrée</button><button className="big-button" onClick={() => move('out')}>Sortie</button><button className="big-button" onClick={() => move('reserved')}>Réserver</button><button className="big-button" onClick={() => move('returned')}>Retour</button><button className="big-button" onClick={() => move('adjust')}>Ajuster</button></div><div className="mt-3 grid gap-2 md:grid-cols-3"><input className="big-field" value={item.minQuantity} onChange={e => updateItem(item.id, { minQuantity: Number(e.target.value) || 0 })} inputMode="decimal" placeholder="Minimum"/><input className="big-field" value={item.reorderQuantity} onChange={e => updateItem(item.id, { reorderQuantity: Number(e.target.value) || 0 })} inputMode="decimal" placeholder="À commander"/><input className="big-field" value={item.unitCost} onChange={e => updateItem(item.id, { unitCost: Number(e.target.value) || 0 })} inputMode="decimal" placeholder="Coût"/></div></div> }